### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by ajpelu** [ajpelu/respineDocencia#1]

**Comment by ajpelu** [comment]
- [x] Crear script para inicializar app
- [x] configure server and ui
- [ ] Añadir biblio 
- [ ] Bib text con biblio
- [x] Configurar server
- [ ] Cambiar aspecto ui (adaptar) 
- [x] Limpiar loader?? 
- [x] Crear init_parameters script
- [x] List all pkgs used
- [ ] Añadir créditos a la app y bibliografía

**Comment by ajpelu** [comment]
update task list

**Comment by ajpelu** [comment]
Se ha añadido un init_parameter script, con muchos de los parametros necesarios que antes estaban en server y en ui. 
La idea es que así, solamente estén en un sitio y no haya que duplicar. 
Por otro lado, en server y en ui se cargan esos parametros al inicio.
